<?php
/**
 * create_case_sheet.php
 * API endpoint to create a new case sheet with automatic field copying from previous case sheet
 */

// Enable error reporting for debugging
error_reporting(E_ALL);
ini_set('display_errors', 0);
ini_set('log_errors', 1);

session_start();
header('Content-Type: application/json');

// TODO: Add authentication check here
// if (!isset($_SESSION['employee_id'])) {
//     echo json_encode(['success' => false, 'message' => 'Unauthorized']);
//     exit;
// }

// Database connection
require_once __DIR__ . '/app/config/database.php';
$pdo = getDBConnection();

// Get JSON input
$input = json_decode(file_get_contents('php://input'), true);

if (!$input) {
    echo json_encode(['success' => false, 'message' => 'Invalid input']);
    exit;
}

$patient_id = $input['patient_id'] ?? null;
$visit_type = $input['visit_type'] ?? 'Follow-up';
$user_id = $input['user_id'] ?? 1; // TODO: Get from session

if (!$patient_id) {
    echo json_encode(['success' => false, 'message' => 'Patient ID required']);
    exit;
}

try {
    // Step 1: Get the most recent previous case sheet for this patient
    $sql = "SELECT * FROM case_sheets 
            WHERE patient_id = :patient_id 
            ORDER BY case_sheet_id DESC 
            LIMIT 1";
    
    $stmt = $pdo->prepare($sql);
    $stmt->execute([':patient_id' => $patient_id]);
    $previousCaseSheet = $stmt->fetch(PDO::FETCH_ASSOC);
    
    // Step 2: Define which fields should be copied (~) vs blank (!)
    // ~ fields: Copy from previous case sheet if it exists, otherwise blank
    // ! fields: Always start blank
    
    $fieldsToCopy = [
        // Personal tab (~)
        'number_of_children',
        'type_of_delivery',
        'delivery_location',
        'delivery_source',
        'has_uterus',
        'menstrual_age_of_onset', // Only copy age of onset, not the cycle details
        // Note: menstrual_cycle_frequency, menstrual_duration_of_flow, menstrual_lmp, menstrual_mh
        // are NOT copied - doctor needs to fill these in fresh each visit (shown as reference only)
        
        // History tab (~)
        'condition_dm',
        'condition_htn',
        'condition_tsh',
        'condition_heart_disease',
        'condition_others',
        'surgical_history',
        'family_history_cancer',
        'family_history_tuberculosis',
        'family_history_diabetes',
        'family_history_bp',
        'family_history_thyroid',
        'family_history_other'
    ];
    
    // Step 3: Build the INSERT query
    $insertFields = [
        'patient_id',
        'visit_datetime',
        'visit_type',
        'status',
        'created_by_user_id'
    ];
    
    $insertValues = [
        ':patient_id' => $patient_id,
        ':visit_datetime' => date('Y-m-d H:i:s'),
        ':visit_type' => $visit_type,
        ':status' => 'OPEN',
        ':created_by_user_id' => $user_id
    ];
    
    // Add fields to copy from previous case sheet
    if ($previousCaseSheet) {
        foreach ($fieldsToCopy as $field) {
            if (isset($previousCaseSheet[$field]) && $previousCaseSheet[$field] !== null && $previousCaseSheet[$field] !== '') {
                $insertFields[] = $field;
                $insertValues[':' . $field] = $previousCaseSheet[$field];
            }
        }
    }
    
    // Build and execute INSERT
    $fieldsList = implode(', ', $insertFields);
    $placeholdersList = implode(', ', array_keys($insertValues));
    
    $sql = "INSERT INTO case_sheets ($fieldsList) VALUES ($placeholdersList)";
    $stmt = $pdo->prepare($sql);
    $stmt->execute($insertValues);
    
    // Get the case_sheet_id that was generated by the trigger
    // Query for the most recent case sheet for this patient
    $stmt = $pdo->prepare("SELECT case_sheet_id FROM case_sheets WHERE patient_id = ? ORDER BY case_sheet_id DESC LIMIT 1");
    $stmt->execute([$patient_id]);
    $newCaseSheetId = $stmt->fetchColumn();
    
    echo json_encode([
        'success' => true,
        'case_sheet_id' => $newCaseSheetId,
        'message' => 'Case sheet created successfully',
        'fields_copied' => count($insertFields) - 5 // Subtract the base fields
    ]);
    
} catch (PDOException $e) {
    error_log('Database error in create_case_sheet.php: ' . $e->getMessage());
    echo json_encode([
        'success' => false,
        'message' => 'Database error: ' . $e->getMessage()
    ]);
}
